name: Release Notes

on:
  pull_request:
    types:
      - closed

jobs:
  update-notion:
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR Content
        uses: actions/checkout@v4

      - name: Capture PR Title, Date and User
        run: |
          PR_TITLE="${{ github.event.pull_request.title }}"
          PR_USER="${{ github.event.pull_request.user.login }}"
          echo "pr_title=$PR_TITLE" >> $GITHUB_ENV
          echo "pr_user=$PR_USER" >> $GITHUB_ENV

          PR_DATE=$(date -u +"%Y-%m-%d")
          echo "pr_date=$PR_DATE" >> $GITHUB_ENV
          
      #     # Check if PR Title is empty
      #     if [[ -z "$PR_TITLE" ]]; then
      #       echo "No PR title found."
      #       exit 0
      #     fi

      #     # Check if PR Title contains feat: and extract the message and trigger the release
      #     if [[ "$PR_TITLE" == *"feat:"* ]]; then
      #       MESSAGE=$(echo "$PR_TITLE" | grep -oP "(?<=feat: ).*")
      #       if [[ -n "$MESSAGE" ]]; then
      #         echo "message=$MESSAGE" >> $GITHUB_ENV
      #       else
      #         echo "No valid feature message found after feat: "
      #         exit 0
      #       fi
      #     else
      #       echo "No feat: found in PR title."
      #       exit 0
      #     fi
          
      # - name: Format Date and Message
      #   id: format_data
      #   run: |
      #     # Get Current Date in ISO 8601
      #     PR_DATE=$(date -u +"%Y-%m-%d")
          
      #     # Prepare Header and Bullet Point Content
      #     echo "pr_date=$PR_DATE" >> $GITHUB_ENV
      #     echo "bullet_point=• $MESSAGE" >> $GITHUB_ENV
